[package]
name = "vdb-wire"
version.workspace = true
edition.workspace = true

[dependencies]
vdb-types.workspace = true
capnp.workspace = true
bytes.workspace = true
thiserror.workspace = true

[build-dependencies]
capnpc.workspace = true
