[package]
name = "vdb-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "vdb-server"
path = "src/main.rs"

[dependencies]
vdb-types.workspace = true
vdb-wire.workspace = true
vdb-runtime.workspace = true
capnp.workspace = true
capnp-rpc.workspace = true
tokio.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
