[package]
name = "vdb-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
bytes.workspace = true
sqlx.workspace = true

[dev-dependencies]
proptest.workspace = true
test-case.workspace = true
