[package]
name = "vdb-kernel"
version.workspace = true
edition.workspace = true

[dependencies]
vdb-types.workspace = true
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
anyhow.workspace = true

[dev-dependencies]
proptest.workspace = true
test-case.workspace = true
