[package]
name = "kmb-admin"
description = "Kimberlite administration CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kmb-admin"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# Internal crates
kimberlite.workspace = true
kmb-types.workspace = true
kmb-client.workspace = true
kmb-wire.workspace = true

# CLI
clap.workspace = true

# Core
anyhow.workspace = true
thiserror.workspace = true

# Output
serde_json.workspace = true
