[package]
name = "vdb-client"
version.workspace = true
edition.workspace = true

[dependencies]
vdb-types.workspace = true
vdb-wire.workspace = true
capnp.workspace = true
capnp-rpc.workspace = true
tokio.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
tracing.workspace = true
