[package]
name = "vdb-crypto"
description = "Cryptographic primitives for VerityDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
thiserror.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
zeroize.workspace = true
subtle.workspace = true
aes-gcm.workspace = true
sha2.workspace = true
