[package]
name = "vdb-admin"
version.workspace = true
edition.workspace = true

[[bin]]
name = "vdb"
path = "src/main.rs"

[dependencies]
vdb-types.workspace = true
vdb-client.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
