[package]
name = "vdb-admin"
description = "VerityDB administration CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "vdb-admin"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
# Internal crates
vdb.workspace = true
vdb-types.workspace = true
vdb-client.workspace = true
vdb-wire.workspace = true

# CLI
clap.workspace = true

# Core
anyhow.workspace = true
thiserror.workspace = true

# Output
serde_json.workspace = true
